version: "3.7"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./data/minio/data:/data
      - ./data/minio/config:/root/.minio
